platform :ios, '10.0'
use_frameworks!

inhibit_all_warnings!

target 'RxSwift Demo' do
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
end

target 'RxSwift DemoTests' do
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'RxTest', '~> 3.0'
  pod 'RxBlocking', '~> 3.0'
end
